### ISSUE TITLE
Slow marshalling of 'deep' EML documents

### ISSUE THREAD

**Issue by gothub** [ropensci/EML#182]
With a fairly simple EML document, the time that is required to marshall the object, i.e. retrieve from memory in preparation for writing to disk, etc. is fairly long. This is really an R issue, but with the complex objects required to represent an EML document, is there any way to improve performance?

Here is are two simple performance tests, the first of which shows a fairly simple document
being read in then printed out to the console. The slow performance is seen when the EML object
is retrieved from memory and printed to the console. The next test shows the dramatic speedup
gained by removing the 'deepest' elements of the document:

## performance test with original document
```'
# Read in document
ptm <- proc.time()
md <- read_eml("~/tmp/test-eml.xml")
proc.time() - ptm
   user  system elapsed 
  2.302   0.033   2.342

# Marshall document and print to console
 ptm <- proc.time()
 md
<eml packageId="urn:uuid:80b12c8f-955e-4ef4-b712-9c86c1401bfb" system="knb" xsi:schemaLocation="eml://ecoinformatics.org/eml-2.1.1 eml.xsd">
  <dataset>
    <title>
      <value>My package title</value>
    </title>
    <creator>
      <individualName>
        <givenName>Smith</givenName>
        <surName>John</surName>
      </individualName>
      <electronicMailAddress>jsmith@example.com</electronicMailAddress>
    </creator>
    <pubDate>2016-11-06</pubDate>
    <abstract>This is an example abstract for the data set. This is only a test.</abstract>
    <contact>
      <individualName>
        <givenName>Smith</givenName>
        <surName>John</surName>
      </individualName>
      <electronicMailAddress>jsmith@example.com</electronicMailAddress>
    </contact>
    <methods>
      <methodStep>
        <description>This is the method description.</description>
      </methodStep>
    </methods>
    <otherEntity>
      <entityName>file53c63f6761a.csv</entityName>
      <physical>
        <objectName>file53c63f6761a.csv</objectName>
        <size unit="bytes">103</size>
        <dataFormat>
          <externallyDefinedFormat>
            <formatName>text/csv</formatName>
          </externallyDefinedFormat>
        </dataFormat>
      </physical>
      <entityType>text/csv</entityType>
    </otherEntity>
    <otherEntity>
      <entityName>file53c49c3d83b.csv</entityName>
      <physical>
        <objectName>file53c49c3d83b.csv</objectName>
        <size unit="bytes">128</size>
        <dataFormat>
          <externallyDefinedFormat>
            <formatName>text/csv</formatName>
          </externallyDefinedFormat>
        </dataFormat>
      </physical>
      <entityType>text/csv</entityType>
    </otherEntity>
  </dataset>
</eml> 
proc.time() - ptm
   user  system elapsed 
  9.378   0.134   9.532 
```

So that's almost 10 seconds for R to retrieve and assemble this document.

## performance test with simplified document
Removing the `<dataFormat>` elements from both `<otherEntities>` speeds things up 
considerably:

```
# Read in document
ptm <- proc.time()
md <- read_eml("~/tmp/test-eml-no-df.xml")
proc.time() - ptm
   user  system elapsed 
  1.050   0.005   1.060 

# Marshall document
 ptm <- proc.time()
 md
<eml packageId="urn:uuid:80b12c8f-955e-4ef4-b712-9c86c1401bfb" system="knb" xsi:schemaLocation="eml://ecoinformatics.org/eml-2.1.1 eml.xsd">
  <dataset>
  ...
</eml>
proc.time() - ptm
   user  system elapsed 
  4.476   0.017   4.505 

```

**Comment by cboettig** [comment]
Yeah, definitely an issue. The next step would be to profile the code of course, e.g. using `Rprof()` and/or `lineprof` and see where the hold up is.  Might be in the S4 class generation; or might be in functions from the `XML` library.  Maybe tweaking the `EML:::XMLtoS4()` internal fn might help.  Now that `xml2` supports writing XML, I've thought about switching to that, though it might be a pain to do so, it would be less major than having to ditch or re-engineer the S4 classes.

Guess we should profile `write_eml` too; or has that always been reasonable?

**Comment by gothub** [comment]
Calling `write_eml` vs outputting the EML object to the console doesn't add significant
amount of elapsed time, so checking `EML:::XMLtoS4()` appears to be the right 
path.

**Comment by amoeba** [comment]
I've experienced this as well with larger EML docs. I just profiled a sluggish doc that takes ~10s to return from a call to `read_eml`. I threw up a `profvis` graph here: http://rpubs.com/brycemecum/read_eml

`write_eml` on this doc (once loaded via `read_eml`) is much slower at ~90s:  http://rpubs.com/brycemecum/write_eml

I don't know the nuances of S4 classes or this package but I thought I'd share the profiles.

**Comment by cboettig** [comment]
Sorry I misread your comment the first time, I thought we were talking parsing speed (XML -> S4), not serializing (S4 -> XML) speed.  I think both are potentially problems.  

Note that 'printing' an eml object to the console is actually the same as serializing the S4; the internal R representation in memory is all S4 structures.  So the function in question is really `EML::S4Toeml`.  

Looks like the biggest culprit is the recursive calls to `isEmpty`, in particular, this line of `isEmpty`: https://github.com/ropensci/EML/blob/master/R/xml-s4.R#L208

That whole function could probably be much improved; it's been a long time since I wrote it; but the logic is somewhat tricky with the deeply nested nature of complex types in EML.

**Comment by cboettig** [comment]
While we should still probably find a faster alternative for `isEmpty`, but sounds like the issue about printing to console will be better resolved by printing some summary object rather than converting the whole shebang to XML and displaying the raw XML (see review comments, #183).  One challenge for this is what to do about subtypes, e.g. a `taxonomicCoverage` class etc.  Writing completely custom summary print methods for every complexType in EML doesn't sound ideal.

**Comment by gothub** [comment]
@cboettig The design goal of printing summary info to the console is an important one, but just to be clear, the use case that prompted this issue was use of `write_eml`, which has to perform the
full marshalling of R objects to XML before writing out via `saveXML`. I was using printing out
a representation of the object to the console as an easily viewable recreation of the issue, independent of any other packages or processing. So in my mind, the more important use case (write_eml) involves converting the entire EML representation to XML.

**Comment by gothub** [comment]
@cboettig Any more thoughts on this issue? I'm seeing about a 20 second wait for calls to
`write_eml()` for a simple EML document, longer for larger documents.

**Comment by cboettig** [comment]
I think the most direct fix would be just to rework the logic for `isEmpty`, it does a lot of probably unnecessarily long recursions to decide if a complex S4 object has any fields.  I'd definitely be happy for a pull request to change that up, I just haven't had a chance to hack at it.  

e.g. currently if you have a complex class like: 

```
- A 
  - B
  - C
     - c1
     - c2
```

it has to descend all the way down the tree to `c1` and `c2` to decide if they are empty (e.g. NULL or empty string values).  This eats almost all of the time.

**Comment by mbjones** [comment]
@cboettig This performance problem is causing us problems still.  Bryce and I discussed solutions, and thought of two possibly half-baked ways of handling it:

## Option 1: boolean flags for empty elements
For each node in the tree, add a special boolean slot `isEmpty` which defaults to `true`. Whenever an assignment is made to a child of that element, set `isEmpty <- FALSE` in the constructor for that node, and walk up the tree of parent nodes setting `isEmpty <- FALSE` until you encounter a node that already is set that way. For a depth 10 tree, this is a minimum of 1 and maximum of 10 additional assignment operations, but should never have to repeat.

During serialization, one would then only have to descend to children of nodes for which `isEmpty == FALSE`, allowing you to skip whole subtrees, and only visit each node once.


## Option 2: Use NA for empty slots
During construction, use initialize() to default all slots to `NA`.  Create accessor methods for all get_ and set_ operations, so that slots are not accessed directly.  Within the accessors, do a check if slots are set to NA when determining how to act.  Again, this would prevent having to descend trees during serialization for which the slot is NA.

Maybe helpful? Maybe other approaches?

**Comment by amoeba** [comment]
I'm a little partial to Option 1 because I like the slots being pre-populated and discoverable. Though I am weary of adding housekeeping logic in other places to manage a flag for emptiness.

As an aside, I wanted to see how many times `isEmpty` gets called when writing out a simple EML object so  I tweaked `isEmpty` to dump its single argument (`obj`) to disk when called. For this document:

```{xml}
<eml>
  <dataset>
    <title>My title</title>
  </dataset>
</eml> 
```

when I call `write_eml(doc, tempfile())`, `isEmpty` is called 84 times in total. With option 1, it seems like it would only need to be called a handful of times. The file I wrote out is [here](https://gist.github.com/amoeba/1385e74fa5b670cea85b5786113bf457). For the file `inst/examples/example-eml-2.1.1.xml"` included in the package, `isEmpty` is called 284 times.

I'd be game for taking a crack at whatever's decided.

**Comment by gothub** [comment]
I vote for option 1 as well, as the`isEmpty` flag approach is more explicit, and it will be clear for someone looking at the code in the future what is being done.

**Comment by cboettig** [comment]
My main concern with creating an `isEmpty` slot is that we'd start running into issues where the flag isn't correctly set; particularly under the current workflow where users are accessing slots directly since we don't have all the accessor / assignment S4 methods in place.  e.g. I think there's no way to automatically update the flag if a user starts with an empty `object` and does `object@slot <- something`, right?  

Ultimately, I think both the current `isEmpty` and the decision to create initialize methods that initialize the child slots was a lazy design choice on my part.  @amoeba is right that currently it can be really useful to have the slots filled out, but that is only because we don't have proper generator and accessor methods.  These should be easier to generate once Gabe's S4Coffee is released ( #197), and we should be able to simplify the current `initialize` methods and restore the more vanilla expected behavior of calling `new("complexObject")` (we'll still want the initialize methods for streamlining the way we use a list for repeating elements).  So this would basically be the `NA` approach.

Even if the slots are initialized instead of being `NA`, we should have sensible behavior (e.g. there's probably no use case for serializing empty XML nodes?)

**Comment by cboettig** [comment]
It may be faster to simply serialize all nodes and then prune empty nodes from the XML, e.g. with a xpath expression such as ` "//*[not(*)][not(normalize-space())]"` ?

**Comment by amoeba** [comment]
That sounds really promising. From the profiling, it looks like removing the calls to `isEmpty` alone would be a nice bump in performance.

**Comment by cboettig** [comment]
Okay, working on a proof-of-principle on this.  I think I can migrate things over to `xml2` at the same time (now that xml2 has write support; I think this will also help on the performance side of things); will require a little debugging to strip out all references to `XML` classes and maybe a few special cases. 

So far I've pushed a version to the `xml2` branch that implements xml2-based method for serializing.  It'll fail on anything with a textType since the docbook-style formating is still an `XML` object, but should work with simple examples.  

As suggested above, there's no `isEmpty` logic any more, I serialize all nodes to XML and then drop them via xPath. It's not obvious this is always faster, particularly if the `isEmpty` recursion could be sped up, but I think it's promising.  could use some profiling a range of test cases.  

Also, I think the `isEmpty` logic is still being used in some of the `get_*` methods to get nodes at arbitrary depth.  Still need to think more about these.  One obvious strategy is to convert all such queries to xpath instead, ideally avoiding a lot of back-and-forth serialization/parsing.

**Comment by amoeba** [comment]
That's really great news @cboettig. The conversion to `xml2` is a big win too so thanks for doing that. Can any of us help at this point? I could make some time next week.

**Comment by cboettig** [comment]
@gothub @amoeba Okay, I have what I think is a functional version (i.e. passes check) on the [`xml2` branch](https://github.com/ropensci/EML/tree/xml2) based on `xml2` which also avoids any `isEmpty` calls in writing out to file.

This version keeps empty nodes until `write_eml` is called, then recursively prunes empty nodes (seems there's no `xpath` for nodes which have children to an arbitrary depth but whose children are empty), but it is called at most only as many times as the maximum node depth and should be way faster even per call than `isEmpty`.  I haven't done any profiling but I think this should speed things up substantially.  Technically this didn't need an `xml2` migration to happen, but wanted to do that anyway and I think it should streamline things later on in any event.  

Please kick the tires and let me know how it goes; I haven't done much testing beyond the still somewhat limited test suite (though most importantly validation and equivalence tests pass on the test eml files in `xsd/test` dir).

**Comment by gothub** [comment]
@cboettig Initial tests look really good. Simple documents with just a few entities no attributes that were taking about 20 seconds to write now take between .5 and 1 second. I'll continue to test with more complex, bigger documents.

I did notice that the `show()` method for `eml` objects renders the object unformatted:

```
> md <- read_eml("/tmp/test-eml.xml")
> show(md)
{xml_document}
<eml packageId="urn:uuid:80b12c8f-955e-4ef4-b712-9c86c1401bfb" system="knb" xmlns:eml="eml://ecoinformatics.org/eml-2.1.1" xmlns:stmml="http://www.xml-cml.org/schema/stmml-1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
[1] <access>\n  <references/>\n</access>
[2] <dataset>\n  <shortName/>\n  <title>\n    <value>My package title</value>\n  </title>\n  <creator>\n    <individualName>\n      <givenName>Smith</givenName>\n      <surName>Jo ...
[3] <citation>\n  <shortName/>\n  <pubDate/>\n  <language/>\n  <series/>\n  <abstract/>\n  <intellectualRights/>\n  <coverage>\n    <references/>\n  </coverage>\n  <article>\n     ...
[4] <software>\n  <shortName/>\n  <pubDate/>\n  <language/>\n  <series/>\n  <abstract/>\n  <intellectualRights/>\n  <coverage>\n    <references/>\n  </coverage>\n  <version/>\n  < ...
[5] <protocol>\n  <shortName/>\n  <pubDate/>\n  <language/>\n  <series/>\n  <abstract/>\n  <intellectualRights/>\n  <coverage>\n    <references/>\n  </coverage>\n  <references/>\n ...
```

**Comment by cboettig** [comment]
Thanks @gothub , that's correct, by default I'm using the XML format (as rendered by `xml2` package) as the `show` method for the S4 objects, since the default S4 render looks even less readable.  

Ideally I think we will want custom `show` (& maybe `summary`) methods for most common objects (e.g. `eml`, `dataset`, `dataTable`, `coverage` `attributeList`, maybe things like all the agent types, citations, etc), which could display a summary of the most relevant information in some pretty text layout.  But meanwhile we also need a basic fallback for how we show any S4 object that doesn't have a summary print method (this is issue #201).  Could really use some suggestions on what you think `show()` should print, both for particular types like `eml` and as the generic default.  

#189 suggests a nice GUI view based on listviewer, which is good for exploring EML but not a substitute for a text based read out.  

What would you suggest?  Should the default `show` render the XML in long form, the way the old XML package does?  `xml2` uses this more compact format which shows mostly  the top level node and it's immediate children, which is probably not ideal (though made worse because it does not call the prune function so it shows all the empty nodes).  On the other hand, it's more compact.

**Comment by amoeba** [comment]
Nice work @cboettig. Writing is certainly a lot faster and this will be a huge improvement for daily workflows at NCEAS. Though with the new approach, the unformatted XML output (as @gothub pointed out) _may_ make current workflows a little more difficult as checking the XML interactively might be a common scenario. Generics for `print`/`show` would be great. I'd prefer them to show indented XML like the old way but I need to ask the team we have using the EML R package now what they could use. I'll come back here with what I find out.

**Comment by amoeba** [comment]
Did some asking, got two answers:

1. Person one makes edits in R using the EML package, runs `eml_validate`, and then just uploads the document to a test site we use in order to check that it looks right on the website before publishing it to the production site.
2. Person two makes edits in R using the EML package and often dumps the entire doc or part of the document to the REPL and cares about the XML output. For attributes, this person often uses the `get_attributes` function to produce a tidy view of an attribute list. For a lot of edits, this person also, as in (1), uploads the EML document to the test site to see how it renders.

These two answers are a bit specific to us and our workflow because we're editing complex EML that can't be viewed all at once as XML and we care about what it looks like when rendered on our website by the aforementioned XSLT. 

I think that the `show` generics should show the full, indented, pruned XML, if that's possible. Though now that I've typed this up, and in light of #189 I'm wondering about using XSLT as a way of viewing the XML. We have a pretty mature EML XSLT that would just need some cleanup to be used for this purpose.

**Comment by amoeba** [comment]
`show` is working great with that latest commit. I poked around a bunch and all is well.

**Comment by gothub** [comment]
When authoring EML I'd really like to see the full, indented XML. This is most useful for selected
elements of the document, for example. just viewing a `dataset`, and I think is necessary for verifying that  constructed the document correctly. So I'm voting for the `show()` methods to output fully rendered, indented XML.

When viewing EML that I'm not familiar with, e.g. downloaded from somewhere, having the 
`listview` or `summary()` functions would be really useful, but for my own use cases of secondary important to using `show()` and seeing the full XML.

**Comment by cboettig** [comment]
Okay, I believe we've addressed the speed issue with the refactor to xml2 and more importantly the reduction of recursive calls to `xml2`. Please re-open otherwise.

There's a secondary issue introduced by moving to `xml2` in that its print methods don't show the full XML tree.  The `xml2::xml_structure()` shows more than the default format, but one has to write the document out to actually see the raw xml.  I think this is a general `xml2` issue and should be addressed there.  Meanwhile we're working on more higher-level `show()` methods for some of the major classes that would have cleaner summary print methods than merely showing the XML anyway.  

Meanwhile, we also have a trial version of listview functionality (see #189)
